# SPDX-License-Identifier: MIT

set(PROGRAM_COMMAND "${PROGRAM}")
if(DEFINED PROGRAM_EMULATOR AND NOT "${PROGRAM_EMULATOR}" STREQUAL "")
    set(PROGRAM_COMMAND ${PROGRAM_EMULATOR} "${PROGRAM}")
endif()
